version: 0.2

phases:

  install:
    commands:
      - mkdir -p build/collectl
      - nohup collectl --ALL -f build/collectl/ci-collectl &
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay >/var/log/docker.log &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - ./gradlew check assemble webappImagePublish ecsImageDefinitions staticSiteS3Publish testReportPublish -s --scan

  post_build:
    commands:
      - pkill collectl

artifacts:
  files:
    - build/imagedefinitions.json
    - build/collectl/**/*
  discard-paths: yes

cache:
  paths:
    - /root/.gradle/native/**/*
    - /root/.gradle/caches/**/*
    - /root/.gradle/nodejs/**/*
    - /root/.gradle/wrapper/**/*
    - /root/.grain/packages/**/*
